export enum ErrorCode {
  EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED",
  FILE_STORAGE_ERROR = "FILE_STORAGE_ERROR",
}
